// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_command/mock_interfaces.go -package=mock_command
//

// Package mock_command is a generated GoMock package.
package mock_command

import (
	context "context"
	reflect "reflect"

	command "github.com/kmatsui058/bookstore-ordering/internal/modules/order/app/command"
	order "github.com/kmatsui058/bookstore-ordering/internal/modules/order/domain/order"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
	isgomock struct{}
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// RunTransaction mocks base method.
func (m *MockTransactionManager) RunTransaction(ctx context.Context, fn func(context.Context, command.TransactionalRepository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockTransactionManagerMockRecorder) RunTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockTransactionManager)(nil).RunTransaction), ctx, fn)
}

// MockTransactionalRepository is a mock of TransactionalRepository interface.
type MockTransactionalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionalRepositoryMockRecorder is the mock recorder for MockTransactionalRepository.
type MockTransactionalRepositoryMockRecorder struct {
	mock *MockTransactionalRepository
}

// NewMockTransactionalRepository creates a new mock instance.
func NewMockTransactionalRepository(ctrl *gomock.Controller) *MockTransactionalRepository {
	mock := &MockTransactionalRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalRepository) EXPECT() *MockTransactionalRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockTransactionalRepository) FindByID(ctx context.Context, orderID order.OrderID) (*order.Aggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, orderID)
	ret0, _ := ret[0].(*order.Aggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTransactionalRepositoryMockRecorder) FindByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTransactionalRepository)(nil).FindByID), ctx, orderID)
}

// SaveEvents mocks base method.
func (m *MockTransactionalRepository) SaveEvents(ctx context.Context, events []order.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvents indicates an expected call of SaveEvents.
func (mr *MockTransactionalRepositoryMockRecorder) SaveEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvents", reflect.TypeOf((*MockTransactionalRepository)(nil).SaveEvents), ctx, events)
}

// SaveSnapshot mocks base method.
func (m *MockTransactionalRepository) SaveSnapshot(ctx context.Context, agg *order.Aggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSnapshot", ctx, agg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSnapshot indicates an expected call of SaveSnapshot.
func (mr *MockTransactionalRepositoryMockRecorder) SaveSnapshot(ctx, agg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSnapshot", reflect.TypeOf((*MockTransactionalRepository)(nil).SaveSnapshot), ctx, agg)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, events []order.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, events)
}
